title: C++ Odyssey
description: A c++ Journey.
theme: just-the-docs

url: https://alexmollard.github.io/CppOdyssey

aux_links:
  GitHub: https://github.com/AlexMollard

color_scheme: dark

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
#markup / liquid-based content.
footer_content: > # accepts markdown
  <p>Site last generated: {{ site.time | date: '%Y-%m-%d' }}</p>

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
