title: C++ Odyssey
description: A C++ Journey.
theme: just-the-docs

url: https://alexmollard.github.io/CppOdyssey

aux_links:
  GitHub: https://github.com/AlexMollard

color_scheme: dark

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
